services:
  external-products-api:
    build: ./product_mcp_server
    container_name: hbntory-external-products-api
    environment:
      HBN_PRODUCTS_PORT: "5000"
      HBN_PRODUCTS_LATENCY_MS: "0"
    ports:
      - "5001:5000"
    restart: unless-stopped

  db:
    container_name: hbntory-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backoffice:
    build: ./backoffice
    container_name: hbntory-backoffice
    environment:
      HBN_BACKOFFICE_PORT: "5000"
      HBN_BACKOFFICE_LATENCY_MS: "0"
      HBN_BACKOFFICE_API_URL: "http://external-products-api:5000"
    ports:
      - "5002:5000"

  mcpserver:
    build: ./product_mcp_server
    container_name: hbntory-mcpserver
    environment:
      HBN_MCP_PORT: "5000"
      HBN_MCP_LATENCY_MS: "0"
      HBN_MCP_API_URL: "http://external-products-api:5000"
    ports:
      - "5003:5000"

  aiservice:
    build: ./ai_service
    container_name: hbntory-aiservice
    environment:
      HBN_AI_PORT: "5000"
      HBN_AI_MCP_URL: "http://mcpserver:5000"
    ports:
      - "5004:5000"

  webclient:
    build: ./client_web
    container_name: hbntory-webclient
    environment:
      HBN_WEB_PORT: "5000"
      HBN_WEB_CLIENT_URL: "http://aiservice:5000"
    ports:
      - "5005:5000"

volumes:
  postgres_data: