import logging
import config
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from agent import ProductQueryAgent
from mcp_client import ProductMCPClient

logging.basicConfig(level=logging.INFO)

mcp_client = ProductMCPClient()
agent = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global agent
    await mcp_client.connect()
    agent = ProductQueryAgent(mcp_client)
    yield

    await mcp_client.close()

app = FastAPI(lifespan=lifespan)

class QueryRequest(BaseModel):
    question: str = Field(..., description="The user's question about products or stock.", min_length=1)

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the agent.")
    tool_calls: list[dict] = Field(default_factory=list, description="List of tool calls made during the query processing.")

@app.post("/query", response_model=QueryResponse)
async def query_endpoint(request: QueryRequest):
    if agent is None:
        raise HTTPException(status_code=503, detail="Agent not initialized.")

    try:
        result = await agent.answer(request.question)
    except Exception:
        logging.exception("Error processing query")
        raise HTTPException(status_code=502, detail="The AI service encountered an internal error.")

    logging.info("Tool calls for question %r: %s", request.question, result["tool_calls"])

    return QueryResponse(
        answer=result["answer"],
        tool_calls=result["tool_calls"] if config.EXPOSE_TOOL_CALLS else [],
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=config.AI_PORT)
